spring.application.name=SessionBillingAPI
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:db}:${POSTGRES_PORT:5432}/${POSTGRES_DB:session_billing}
spring.datasource.username=${POSTGRES_USER:session_billing}
spring.datasource.password=${POSTGRES_PASSWORD:session_billing_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=none
